name: KiCad CI

on:
  workflow_dispatch:
    inputs:
      job:
        description: "Select job to run"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - deploy
          - blend
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    if: ${{ inputs.job == 'all' || inputs.job == 'deploy' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find project, schematic, and PCB files
        id: find_files
        run: |
          project_file=$(find . -type f -name "*.kicad_pro" | head -n 1)
          if [ -z "$project_file" ]; then exit 1; fi
          base_name=$(basename "$project_file" .kicad_pro)
          schematic_file="./${base_name}.kicad_sch"
          pcb_file="./${base_name}.kicad_pcb"
          if [ ! -f "$schematic_file" ] || [ ! -f "$pcb_file" ]; then exit 1; fi
          echo "base_name=$base_name" >> $GITHUB_ENV
          echo "schematic_file=$schematic_file" >> $GITHUB_ENV
          echo "pcb_file=$pcb_file" >> $GITHUB_ENV

      # Rest of the deploy steps...

  generate-blend:
    if: ${{ inputs.job == 'all' || inputs.job == 'blend' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List Gerber files in fab directory
        run: |
          echo "Listing Gerber files in the fab directory:"
          ls -l fab/*.gbr

      - name: Install dependencies (gerbv, inkscape, python3.11, pipx)
        run: |
          sudo apt update
          sudo apt install -y \
            gerbv \
            inkscape \
            python3.11 \
            python3.11-venv \
            python3.11-dev \
            python3-pip \
            curl
            
          # Install pipx for Python package isolation
          python3.11 -m pip install --upgrade pip
          python3.11 -m pip install pipx
          python3.11 -m pipx ensurepath

      - name: Install gerber2blend
        run: |
          # Using pipx to install gerber2blend in an isolated environment
          python3.11 -m pipx install git+https://github.com/antmicro/gerber2blend.git

      - name: Generate .blend file
        run: |
          # Call gerber2blend without arguments to use the default output folder `fab/`
          gerber2blend

      - name: Upload .blend file
        uses: actions/upload-artifact@v3
        with:
          name: blend-file
          path: fab/
