name: KiCad CI

on:
  workflow_dispatch:  # Manually trigger the workflow
  push:
    branches:
      - master  # Trigger on push to master branch
      - main    # Trigger on push to main branch
  pull_request:
    branches:
      - master  # Trigger on pull requests targeting master branch
      - main    # Trigger on pull requests targeting main branch

permissions:
  contents: write  # Ensure write access for the repository contents

jobs:
  # Job to validate files
  validate:
    runs-on: ubuntu-latest
    outputs:
      project_file: ${{ steps.find_files.outputs.project_file }}
      schematic_file: ${{ steps.find_files.outputs.schematic_file }}
      pcb_file: ${{ steps.find_files.outputs.pcb_file }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find project, schematic, and PCB files
        id: find_files
        run: |
          # Find the .pro project file
          project_file=$(find . -type f -name "*.kicad_pro" | head -n 1)
      
          if [ -z "$project_file" ]; then
            echo "No project file found!"
            exit 1
          fi
      
          # Extract the project name from the .pro file (remove the extension)
          base_name=$(basename "$project_file" .kicad_pro)
      
          # Find the corresponding schematic and PCB files based on the project name
          schematic_file="./${base_name}.kicad_sch"
          pcb_file="./${base_name}.kicad_pcb"
          
          if [ ! -f "$schematic_file" ]; then
            echo "Schematic file $schematic_file does not exist!"
            exit 1
          fi
      
          if [ ! -f "$pcb_file" ]; then
            echo "PCB file $pcb_file does not exist!"
            exit 1
          fi
      
          echo "Found project file: $project_file"
          echo "Found schematic file: $schematic_file"
          echo "Found PCB file: $pcb_file"
      
          # Set environment variables to pass to other jobs
          echo "project_file=$project_file" >> $GITHUB_ENV
          echo "schematic_file=$schematic_file" >> $GITHUB_ENV
          echo "pcb_file=$pcb_file" >> $GITHUB_ENV

  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Find schematic and project files
      - name: Find schematic and project files
        id: find_files
        run: |
          # Find the .pro project file
          project_file=$(find . -type f -name "*.kicad_pro" | head -n 1)
      
          if [ -z "$project_file" ]; then
            echo "No project file found!"
            exit 1
          fi
      
          # Extract the project name from the .pro file (remove the extension)
          base_name=$(basename "$project_file" .kicad_pro)
      
          echo "Found project file: $project_file"
          echo "Extracted project name: $base_name"
      
          # Find the corresponding schematic file based on the project name
          root_schematic_file="./${base_name}.kicad_sch"
          
          if [ ! -f "$root_schematic_file" ]; then
            echo "Schematic file $root_schematic_file does not exist!"
            exit 1
          fi
      
          echo "Found root schematic file: $root_schematic_file"
      
          # Store the root schematic file path for later use
          echo "root_schematic_file=$root_schematic_file" >> $GITHUB_ENV
          echo "base_name=$base_name" >> $GITHUB_ENV

      # Step 3: Install KiCad V8.0.0 (or adjust version if necessary)
      - name: Install KiCad V8.0.0 (or adjust version if necessary)
        run: |
          # Add KiCad repository for the correct version
          sudo add-apt-repository ppa:kicad/kicad-8.0-releases -y
          sudo apt update
          sudo apt install -y kicad

      # Step 4: Generate the PDF from the schematic
      - name: Generate schematic PDF
        run: |
          # Ensure the 'doc' directory exists
          mkdir -p doc
          
          # Generate the schematic PDF with the project name dynamically inserted
          kicad-cli sch export pdf --output "doc/${{ env.base_name }}-schematic.pdf" ${{ env.root_schematic_file }}
      
          # Check if the PDF was generated successfully
          if [ ! -f "doc/${{ env.base_name }}-schematic.pdf" ]; then
            echo "Error: schematic PDF was not generated."
            exit 1
          fi
          echo "Schematic PDF generated successfully."

      - name: Configure Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      
      - name: Commit and push the generated PDF
        run: |
          # Add the newly generated PDF to Git
          git add "doc/${{ env.base_name }}-schematic.pdf"
          
          # Check if there are changes to commit
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          
          # Commit if the file was added
          git commit -m "Add generated schematic PDF"
          
          # Push the commit
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
